// @flow

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const ADD_INITIAL_API_DATA = 'ADD_INITIAL_API_DATA'
export const ADD_MORE_API_DATA = 'ADD_MORE_API_DATA'
export const ADD_DETAILS = 'ADD_DETAILS'
export const SET_IS_LOADING = 'SET_IS_LOADING'
export const INCREMENT_CURRENT_PAGE = 'INCREMENT_CURRENT_PAGE'
export const RESET_CURRENT_PAGE = 'RESET_CURRENT_PAGE'